/*
	AOGetImageResponse.h
	The interface definition of properties and methods for the AOGetImageResponse object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface AOGetImageResponse : SoapObject
{
	NSString* _errorCode;
	NSString* _errorText;
	NSString* _email;
	NSData* _imageData;
	double _networkLoad;
	
}
		
	@property (retain, nonatomic) NSString* errorCode;
	@property (retain, nonatomic) NSString* errorText;
	@property (retain, nonatomic) NSString* email;
	@property (retain, nonatomic) NSData* imageData;
	@property double networkLoad;

	+ (AOGetImageResponse*) newWithNode: (NSXMLNode*) node;
	- (id) initWithNode: (NSXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
