/*
	AOGetImageResponse.h
	The implementation of properties and methods for the AOGetImageResponse object.
	Generated by SudzC.com
*/
#import "AOGetImageResponse.h"

@implementation AOGetImageResponse
	@synthesize errorCode = _errorCode;
	@synthesize errorText = _errorText;
	@synthesize email = _email;
	@synthesize imageData = _imageData;
	@synthesize networkLoad = _networkLoad;

	- (id) init
	{
		if(self = [super init])
		{
			self.errorCode = nil;
			self.errorText = nil;
			self.email = nil;
			self.imageData = nil;

		}
		return self;
	}

	+ (AOGetImageResponse*) newWithNode: (NSXMLNode*) node
	{
		if(node == nil) { return nil; }
		return (AOGetImageResponse*)[[AOGetImageResponse alloc] initWithNode: node];
	}

	- (id) initWithNode: (NSXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.errorCode = [Soap getNodeValue: node withName: @"errorCode"];
			self.errorText = [Soap getNodeValue: node withName: @"errorText"];
			self.email = [Soap getNodeValue: node withName: @"email"];
			self.imageData = [Soap dataFromString: [Soap getNodeValue: node withName: @"imageData"]];
			self.networkLoad = [[Soap getNodeValue: node withName: @"networkLoad"] doubleValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"GetImageResponse"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.errorCode != nil) [s appendFormat: @"<errorCode>%@</errorCode>", [[self.errorCode stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.errorText != nil) [s appendFormat: @"<errorText>%@</errorText>", [[self.errorText stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.email != nil) [s appendFormat: @"<email>%@</email>", [[self.email stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.imageData != nil) [s appendFormat: @"<imageData>%@</imageData>", [Soap getBase64String: self.imageData]];
		[s appendFormat: @"<networkLoad>%@</networkLoad>", [NSString stringWithFormat: @"%f", self.networkLoad]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[AOGetImageResponse class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}

@end
