/*
	AOServices.h
	Creates a list of the services available with the AO prefix.
	Generated by SudzC.com
*/
#import "AOService1.h"

@interface AOServices : NSObject {
	BOOL logging;
	NSString* server;
	NSString* defaultServer;
AOService1* service1;

}

-(id)initWithServer:(NSString*)serverName;
-(void)updateService:(SoapService*)service;
-(void)updateServices;
+(AOServices*)service;
+(AOServices*)serviceWithServer:(NSString*)serverName;

@property (nonatomic) BOOL logging;
@property (nonatomic, retain) NSString* server;
@property (nonatomic, retain) NSString* defaultServer;

@property (nonatomic, retain, readonly) AOService1* service1;

@end
			