/*
	AOService1.h
	The interface definition of classes and methods for the Service1 web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "AOGetImageResponse.h"

/* Interface for the service */
				
@interface AOService1 : SoapService
		
	/* Returns AOGetImageResponse*.  */
	- (SoapRequest*) getImage2: (id <SoapDelegate>) handler sessionId: (NSString*) sessionId name: (NSString*) name;
	- (SoapRequest*) getImage2: (id) target action: (SEL) action sessionId: (NSString*) sessionId name: (NSString*) name;

	/* Returns AOGetImageResponse*.  */
	- (SoapRequest*) getImage: (id <SoapDelegate>) handler email: (NSString*) email password: (NSString*) password name: (NSString*) name;
	- (SoapRequest*) getImage: (id) target action: (SEL) action email: (NSString*) email password: (NSString*) password name: (NSString*) name;

		
	+ (AOService1*) service;
	+ (AOService1*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	